# -- 코드를 입력하세요
# SELECT 
# # F.FLAVOR
# *
# FROM FIRST_HALF F
# JOIN ICECREAM_INFO I
# ON F.FLAVOR = I.FLAVOR
# WHERE F.TOTAL_ORDER >= 3000 AND I.INGREDIENT_TYPE = 'fruit_based'
# ORDER BY F.TOTAL_ORDER DESC;
SELECT 
    F.FLAVOR
FROM FIRST_HALF F
JOIN ICECREAM_INFO I
    ON F.FLAVOR = I.FLAVOR
WHERE F.TOTAL_ORDER > 3000      -- >=가 아닌 > 를 쓰는 게 대부분 정답 처리 기준
  AND I.INGREDIENT_TYPE = 'fruit_based'
ORDER BY F.TOTAL_ORDER DESC;
